- name: deploying conatiner
  hosts: ans-host
  become: true
  
  tasks:
     - name: stop tomcat docker
       shell: docker stop tomcat-container
       
     - name: remove tomcat container
       shell: docker rm -f tomcat-container
       
     - name: Remove tomcat image
       shell: docker rmi -f softbayx/hello-world
       
     - name: create a new tomcat container using the defined Dockerfile
       shell: docker run -d --name tomcat-container -p 1225:8080 softbayx/caltech-pg-devops-final-capstone-project
